// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjfzfolrvqdlrpwakbcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZnpmb2xydnFkbHJwd2FrYmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTM5ODMsImV4cCI6MjA2NjY4OTk4M30.EE-2TrAw8bLDKeiRrraBsRsXVaHlvcYWvF7IWiTubhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});